### ISSUE TITLE
请教如何在HASS的“能源”里正确设置

### ISSUE THREAD

**Issue by phoenixxie0** [CubicPill/china_southern_power_grid_stat#11]
请教如何在HASS的“能源”里正确设置。我直接添加实体，然后只会显示变动的量，无法显示总电量
![image](https://user-images.githubusercontent.com/1797318/232203252-bc78b115-0ebe-4021-b06a-d7b314d56a13.png)

**Comment by CubicPill** [comment]
HA的”能源“只能追踪增量（以kwh为单位），而且无法更新历史用电量，能接入的只有本月累计用电量和本年度累计用电量。另外南网一般第二天才会更新前一天的数据，所以反映到每日数据上肯定有延迟，这个插件的数据建议只作展示用，要加入能源面板还是建议装个智能电表。
