### ISSUE TITLE
添加后AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setups'

### ISSUE THREAD

**Issue by qsx313** [CubicPill/china_southern_power_grid_stat#2]
Error setting up entry CSG-8888888 for china_southern_power_grid_stat

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/china_southern_power_grid_stat/__init__.py", line 84, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setups'

**Comment by CubicPill** [comment]
应该是版本过低导致，参考：https://developers.home-assistant.io/blog/2022/07/08/config_entry_forwards/
建议：升级到2022.8及以上版本
另外我也会在README中补充相关说明，感谢！

**Comment by qsx313** [comment]
谢谢，你的邮件我已经收到了，我会注意查看。--------------------------郑云飞
