### ISSUE TITLE
大佬，又出现以下几个错误

### ISSUE THREAD

**Issue by fangguisheng** [CubicPill/china_southern_power_grid_stat#5]
此错误来自自定义集成。

Logger: custom_components.china_southern_power_grid_stat.sensor
Source: custom_components/china_southern_power_grid_stat/sensor.py:414
Integration: China Southern Power Grid Statistics (documentation, issues)
First occurred: 下午9:07:29 (1 occurrences)
Last logged: 下午9:07:29

Error fetching data in coordinator: function get_yesterday_kwh, <CSGAPIError sta=01 message=用户日电量外部接口查询异常>

此错误来自自定义集成。

Logger: custom_components.china_southern_power_grid_stat.sensor
Source: helpers/update_coordinator.py:151
Integration: China Southern Power Grid Statistics (documentation, issues)
First occurred: 下午9:07:20 (1 occurrences)
Last logged: 下午9:07:20

Error fetching CSG Account 156xxxxxxxx data: Unexpected exception:

此错误来自自定义集成。

Logger: custom_components.china_southern_power_grid_stat.sensor
Source: custom_components/china_southern_power_grid_stat/sensor.py:549
Integration: China Southern Power Grid Statistics (documentation, issues)
First occurred: 下午9:07:20 (1 occurrences)
Last logged: 下午9:07:20

Unexpected exception:

此错误来自自定义集成。

Logger: custom_components.china_southern_power_grid_stat.sensor
Source: custom_components/china_southern_power_grid_stat/sensor.py:412
Integration: China Southern Power Grid Statistics (documentation, issues)
First occurred: 下午9:07:03 (1 occurrences)
Last logged: 下午9:07:03

Error fetching data in coordinator: function get_balance_and_arrears, <CSGAPIError sta=99999 message=None>

**Comment by fangguisheng** [comment]
卸载后首次绑定可以获取数据，等下次更新的时候就报错了

**Comment by CubicPill** [comment]
麻烦提供一下原始日志(`homeassistant.log` 中的内容)，另外如果方便的话，也麻烦复现一下这个错误并提供一下debug日志，开启debug的方法如下：

在`configuration.yaml`中添加
```yaml
logger:
  default: warning
  logs:
    custom_components.china_southern_power_grid_stat: debug
```

**Comment by CubicPill** [comment]
😂目前没有群也没测试团队，一直就是我一个人测试，然后看论坛上面的反馈

**Comment by no1guyguy** [comment]
你好，我是南网广东省城用户，在APP端重置登录密码后，在集成登录页面输入手机和密码后提示用户名或密码错误，用手机验证码同样不能登陆，但在APP或WEB端登录正常。

**Comment by CubicPill** [comment]
> 你好，我是南网广东省城用户，在APP端重置登录密码后，在集成登录页面输入手机和密码后提示用户名或密码错误，用手机验证码同样不能登陆，但在APP或WEB端登录正常。

应该是南网系统的问题，如果网页端能用手机和密码正常登陆，按理说插件也不应该有问题，如果过了几天还没恢复的话我去复现一下试试
