### ISSUE TITLE
有没有配套的每日电量曲线图卡片啊

### ISSUE THREAD

**Issue by chneez** [CubicPill/china_southern_power_grid_stat#7]
这个卡片不太会弄

**Comment by CubicPill** [comment]
暂时没有默认配套的卡片，不过在论坛里有坛友弄过一个，可以参考
https://bbs.hassbian.com/forum.php?mod=redirect&goto=findpost&ptid=18578&pid=499592

**Comment by chneez** [comment]
这个曲线图搞不定哇，
    - entity: sensor.04XXXXX5341_last_year_total_usage
        data_generator: |
          return entity.attributes.month.map((item, index) => {
           return [new Date(item).getTime(), entity.attributes.kwh[index]];
          });
