### ISSUE TITLE
安装后有一个实体显示不可用

### ISSUE THREAD

**Issue by harry3633** [CubicPill/china_southern_power_grid_stat#8]
安装登录后一共10个实体，其中9个都显示正常，有数据。
但 sensor.094**************_last_month_total_usage
这个实体状态显示是不可用，我是深圳用户
系统也重启过了，请教一下是什么问题，谢谢！

**Comment by harry3633** [comment]
日志：
此错误来自自定义集成。

Logger: custom_components.china_southern_power_grid_stat.sensor
Source: custom_components/china_southern_power_grid_stat/sensor.py:452
Integration: China Southern Power Grid Statistics (documentation, issues)
First occurred: 15:49:44 (3 occurrences)
Last logged: 16:49:03

Error fetching data in coordinator: function get_month_daily_usage_detail, <CSGAPIError sta=02 message=系统异常，请重试>

**Comment by CubicPill** [comment]
已修复（[9d364e6](9d364e632bf8737a98b5507c3ffd3efab63e2788)），请在HACS中更新新版

**Comment by harry3633** [comment]
更新OK，感谢！
