### ISSUE TITLE
正在启动“China Southern Power Grid Statistics”的配置向导，请稍候

### ISSUE THREAD

**Issue by baohuiming** [CubicPill/china_southern_power_grid_stat#9]
添加集成失败，一直卡在‘正在启动“China Southern Power Grid Statistics”的配置向导，请稍候’的页面。日志里没有报错。

**Comment by xinghusp** [comment]
兄弟，我更新到最新版的HACS后解决了此问题，供参考

**Comment by bjtu-bhm** [comment]
> 兄弟，我更新到最新版的HACS后解决了此问题，供参考
我的HACS和HA都是最新版：
HACS 1.30.1
Home Assistant 2023.1.7
在配置向导时出现以下错误：
无法加载配置向导: <html> <head><title>504 Gateway Time-out</title></head> <body bgcolor="white"> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx/1.14.0 (Ubuntu)</center> </body> </html>

**Comment by xinghusp** [comment]
换一个时间试试吧，或者换个网络环境

bjtu-bhm ***@***.***> 于2023年2月5日周日 16:37写道：

**Comment by LOVE2CMOL** [comment]
无法加载配置向导: <html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx</center> </body> </html>      

我也出现了这个问题
